export const headerStr = {
  miniTitle: '  با عضویت در فیت لند اولین ارسال را مهمون ما باش :)',
  logo: 'فروشگاه لوازم ورزشی فیت لند',
  search: 'جستجو',
  signup: 'ثبت نام',
  signin: 'ورود',
  newProduct: 'جدیدترین محصولات',
  offers: 'تخفیفات ویژه',
  mostPopular: 'پر فروش ترین ها',
  sportTools: 'وسایل ورزشی',
  men: 'مردانه',
  women: 'زنانه',
  kids: 'بچگانه',
  bannerText: 'راحت و مطمئن خرید کنید!',
  bannerTitle: 'همراه تو در مسیر سلامتی',
  bannerDesc:
    'بزرگترین حراج فصل فیت لند همین حالا شرع کن و محصولات با یه تخفیف شگفت انگیز بخر!',
  bannerBigTitle: 'سهم بزرگ خودتان را امروز بگیرید!',
  bennerBtn: 'مشاهده محصولات',
};
